ARG FEDORA_VERSION=41

FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION} AS builder

WORKDIR /build-final

ENV CARGO_HOME=/build/.cargo
RUN dnf install -y cargo
RUN mkdir /build && cargo install xh --locked
RUN cp ${CARGO_HOME}/bin/xh /build-final

FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

ARG NAME=my-fedora-toolbox
LABEL com.github.containers.toolbox="true" \
        name="$NAME" \
        version="$VERSION" \
        usage="This image is meant to be used with the toolbox(1) command" \
        summary="Image for creating Fedora Toolbx containers"

WORKDIR /build-final

COPY ./packages.txt .
RUN dnf --assumeyes update && \
        dnf copr enable varlad/zellij -y && \
        dnf --assumeyes install $(cat packages.txt) && \
        wget https://download.docker.com/linux/fedora/docker-ce.repo -O /etc/yum.repos.d/docker-ce.repo && \
        dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y && \
        dnf clean all

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    && echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" \
    | tee /etc/yum.repos.d/vscode.repo

RUN sudo dnf in code -y


COPY --from=builder /build-final/xh /usr/bin/xh

RUN wget https://raw.githubusercontent.com/ducaale/xh/master/completions/xh.fish -O /usr/share/fish/completions/xh.fish
RUN rm -r /build-final


